version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Pre build phase started on `date`
      - echo Move link manager script to folder as index.js
      - mkdir /tmp/linkmanager
      - mv ./src/linkmanager.js /tmp/linkmanager/index.js
      - echo Move redirect service to folder as index.js
      - mkdir /tmp/redirectsvc
      - mv ./src/redirectsvc.js /tmp/redirectsvc/index.js
      - echo Pre build phase completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Install short link dependencies for link manager
      - cd /tmp/linkmanager
      - npm install short-unique-id@4.4.4
      - echo Create zip archive for link manager
      - zip -r /tmp/linkmanagerdeploy.zip .
      - echo Create zip archive for redirect service
      - cd /tmp/redirectsvc
      - zip -r /tmp/redirectsvcdeploy.zip .
      - echo Build completed `date`
  post_build:
    commands:
      - echo Lambda versions publishing started on `date`
      - cd ..
      - echo Publish version to lambda for link manager
      - cd /tmp
      - aws lambda update-function-code --function-name $SHORT_LINKS_MANAGER_FUNCTION_NAME --zip-file fileb://./linkmanagerdeploy.zip --publish
      - echo Publish version to lambda for redirect service
      - aws lambda update-function-code --function-name $SHORT_LINKS_REDIRECT_SERVICE_FUNCTION_NAME --zip-file fileb://./redirectsvcdeploy.zip --publish
      - echo Returning to build folder to deploy error pages to CloudFront
      - echo $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/src
      - echo Copying error pages to S3
      - aws s3 cp . s3://$SHORT_LINKS_ERROR_PAGES_BUCKET_NAME/ --recursive
      - echo Lambda versions publishing completed on `date`