version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Pre build phase started on `date`
      - echo Create new folder for link manager
      - mkdir linkmanager
      - echo Move link manager script to folder
      - mv ./src/linkmanager.js linkmanager/linkmanager.js
      - echo Pre build phase completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - cd linkmanager
      - echo Install short link dependencies for link manager
      - npm install short-unique-id
      - echo Delete package lock and package json files
      - rm package*.json
      - echo Create zip archive
      - zip -r ../linkmanagerdeploy.zip .
      - echo completed finished on `date`
  post_build:
    commands:
      - echo No post build commands required
artifacts:
  name: $env-short-links-service
  files:
    - recirectsvc.js
    - error403.html
    - error404.html
    - linkmanagerdeploy.zip
  discard-paths: yes
  base-directory: src