version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Pre build phase started on `date`
      - echo Create new folder for link manager
      - mkdir linkmanager
      - echo Move link manager script to folder
      - mv ./src/linkmanager.js linkmanager/linkmanager.js
      - echo Pre build phase completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - echo Install short link dependencies for link manager
      - cd linkmanager
      - npm install short-unique-id
      - echo Create zip archive for link manager
      - zip -r ../linkmanagerdeploy.zip .
      - echo Create zip archive for redirect service
      - cd ../src
      - zip -r ../redirectsvcdeploy.zip redirectsvc.js
      - echo Build completed `date`
  post_build:
    commands:
      - echo Lambda versions publishing started on `date`
      - cd ..
      - echo Publish version to lambda for link manager
      - aws lambda update-function-code --function-name $env'ShortLinksManager' --zip-file fileb://./linkmanagerdeploy.zip --publish
      - echo Publish version to lambda for redirect service
      - aws lambda update-function-code --function-name $env'ShortLinksRedirectService' --zip-file fileb://./redirectsvcdeploy.zip --publish
      - echo Lambda versions publishing completed on `date`